# set options
set -g mouse on

# image.nvim
set -gq allow-passthrough on
set -g visual-activity off

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Resize panes with Alt + Arrow keys
bind -n M-Up    resize-pane -U 2
bind -n M-Down  resize-pane -D 2
bind -n M-Left  resize-pane -L 2
bind -n M-Right resize-pane -R 2

# Ctrl Alt vim keys to switch windows
unbind -n C-M-h
unbind -n C-M-l

bind -n C-M-h previous-window
bind -n C-M-l next-window

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Open panes in current directory 
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# ==========================================
# COLOR THEME & STYLING
# ==========================================

# Bottom bar base colors (Abyssal Frost base)
set -g status-style bg=#140A2C,fg=#6FB9DB

# Selection mode colors (Deep Purple background, Bright text)
set -g mode-style "bg=#4A4997,fg=#c6c6cf"

# Pane borders
set -g pane-border-style fg=#6a6c82           # Inactive pane (Muted Gray)
set -g pane-active-border-style fg=#6FB9DB    # Active pane (Bright Cyan)

# Window tabs
set-window-option -g window-status-style fg=#8B6898                    # Inactive tab (Amethyst)
set-window-option -g window-status-current-style bg=#2D53A8,fg=#c6c6cf,bold # Active tab (Strong Blue, Bright text)

# Command prompt / Message line
set -g message-style bg=#1b1e41,fg=#6FB9DB    # Base background, Cyan text

# Remove overrides
set -g status-left-style default
set -g status-right-style default

# Clean up the window tabs (remove the * and - flags)
set-window-option -g window-status-current-format " #I:#W "
set-window-option -g window-status-format " #I:#W "

# renumber indexes windows upon a window close
set-option -g renumber-windows on

# ==========================================

run '~/.tmux/plugins/tpm/tpm'
