[colors.primary]
foreground = "#e8eefc"
background = "#050505"

[colors.normal]
black   = "#1a1a1a"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#00bfff"
blue    = "#4f83ff"
magenta = "#bd93f9"
cyan    = "#00d4ff"
white   = "#cfd8e3"

[colors.bright]
black   = "#44475a"
red     = "#ff6e6e"
green   = "#69ff94"
yellow  = "#66ffff"
blue    = "#6aa8ff"
magenta = "#d6acff"
cyan    = "#99ffff"
white   = "#ffffff"
