# Core Services
exec-once = waybar
exec-once = swaync
exec-once = hypridle
exec-once = hyprpaper

# Connectivity & Audio
exec-once = nm-applet
exec-once = nmcli radio wifi on
exec-once = bluetoothctl power on
exec-once = pactl set-source-mute @DEFAULT_SOURCE@ 1 

# Clipboard Management (cliphist)
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

# Notification Daemon Check (Optional)
exec-once = swaync-client -df
