# preload = ~/Pictures/wallpapers/guts_pc_wallpaper.jpg
# wallpaper =,  ~/Pictures/wallpapers/guts_pc_wallpaper.jpg
# preload = ~/Pictures/wallpapers/berserk.webp
# wallpaper =,  ~/Pictures/wallpapers/berserk.webp
preload = ~/Pictures/wallpapers/guts.jpg
wallpaper =,  ~/Pictures/wallpapers/guts.jpg
