-- Generated by hyprconf2lua v1.3.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Main Hyprland Config

require("variables")

require("monitors")

require("env")

require("autostart")

require("look")

require("input")

require("binds")

require("rules")
